teamcity-client.version=2.0.92
github-api.version=1.327
okhttp.version=4.12.0
octopus-components-registry-service.version=3.0.4
octopus-release-management.version=2.0.28
octopus-oc-template.version=2.0.8

teamcity-2022.image-tag=2022.04.7
teamcity-2026.image-tag=2026.1

test.platform=docker
docker.registry=docker.io
octopus.github.docker.registry=ghcr.io
okd.active-deadline-seconds=1800
okd.project=
okd.cluster-domain=
okd.web-console-url=
okd.service-account-anyuid=teamcity