eureka:
  client:
    enabled: false

server:
  port: 4567

components-registry:
  vcs:
    enabled: false
  work-dir: /components-registry
  groovy-path: ${components-registry.work-dir}
  main-groovy-file: Aggregator.groovy
  supportedGroupIds: corp.domain
  supportedSystems: NONE,CLASSIC
  version-name:
    service-branch: serviceCBranch
    service: serviceC
    minor: minorC
  product-type:
    c: PT_C
    k: PT_K
    d: PT_D
    ddb: PT_D_DB

repositoryPath: /whiskey-builds
supportedGroupIds: corp.domain
supportedSystems: NONE,CLASSIC


logging:
  level:
    org.octopusden.octopus.escrow: DEBUG
    org.octopusden.octopus.crs: DEBUG
    org.octopusden.octopus.components.registry: DEBUG