version: '3'

services:
  teamcity:
    image: ${DOCKER_REGISTRY}/jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8111:8111"
    volumes:
      - ./../build/teamcity-server/datadir:/data/teamcity_server/datadir
      - ./../build/teamcity-server/logs:/opt/teamcity/logs
    healthcheck:
      test: curl -u admin:admin -f teamcity:8111/app/rest/server >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5