apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: teamcity-pvc-template
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${DEPLOYMENT_PREFIX}-teamcity${TEAMCITY_ID}-datadir
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
parameters:
  - description: Unique deployment prefix
    name: DEPLOYMENT_PREFIX
    required: true
  - description: TeamCity instance identifier
    name: TEAMCITY_ID
    required: true