name: Gradle Build & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@v2.1.8
    with:
      flow-type: public
      java-version: '17'
